language: node_js
node_js:
- '8'
before_install:
- npm install -g redoc-cli
script:
- redoc-cli bundle openapi.yaml --output build/index.html --cdn --title "Brave New Coin API documentation" --template template.hbs
- cp -R images build/
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  bucket: docs.bravenewcoin.com
  skip_cleanup: true
  region:
    secure: YkBI8fTtuBvbGjUIuxA+eLtWtUt96JLcFSVXImbrlck0/dgWvPVbR2poF93kqj4G7qXwVdhFk6gPw0fqAcSaDgaF4gUGvGVCLfjMW0l+cLbvLRDU8nwHGEQ6ObRSh8pDtuag77XrT6X4bm9k8NIJ1OIuGr8hkv3rPHqZEUlrETu+7ohToF2yx4bOj+eMBr/etuXnMolD5P/nIxb/eo3DYLp2vwW4pdP9F8pHvTqT6Z8dlFHGhRENjcJlyX7k+wytpxn1b/OXPV5edXo8F4Q0sqojoIL0t7S7vA88F0qzH0ybtjPg4KEcsL2WqHb5jQCc7Je5oDWRc/BJWjnNmjoxWx2i/6uHFHt78QItwPG3GAB7BVaM5ARfEvhZK5w3PJn5WhOErAS4guZV6juJsnfVgW0PKM02iO1eBfUVQTaGxFYSRiyGA67SxMdnq0zjro118WlsB3cv0hxVG0+iE3+A23xxtcvWcgnkfpj+xXLyeuD7+cUKYbhboxs1rwaSAhb8iDHNokewl8+x1id7gxqUZz/xngyRGbjZUddEA9XNj8V0F/kAd2+zltns0e5RdJDPWqWnrhKiFzVOnx8nH+60LocOODHCC67EjoMvfNEzsb4re1wQFisZtShqkc7fW7QAHi/YG8aDfbG2qCg3WVMe3j1Yak5b15H6fF9WGNKXr/k=
  local_dir: build
  acl: public_read
  access_key_id:
    secure: rMuXQDp+00Ua3rU+f+Z+aOuddN0pyXNZBD+moCHOL1v3QpScmT1NRmfDfNn1IdZlfFYLxNaxTedEIBqG9Nqi0wCitTinmum3YBlEZHSqaadnbdo1uKr55b+/LTx25hyCAr7zAzBqF7Pi2zIusF3fAjrSp3bHlOi85aspXcJMhumhenRFe2wCHzAjw7vpPjUYz0YmRQ0VbiD2+4ecn0rHGgv/NhQl/+SKKtXccfF5XEW6JqwxvZbfGjjHvh9xXPk5+QQSy+PdzmsEZzAQkkSNE/ScuC6ZjaFMtXmZNTyDYttLWRk/4dV8zTN/6+4QYExgc4QeOIsllI43gnHbyZrQ9QNkrw3ntZBddP4aMwzWlNStcgX7hJrJX+Ct1ZKe/ShLN8Hp165bknrMWb1cZCiqyYAKlHKPJXo+lLJ4JMLDeCMu5BBRj31ToxXFxEjw7B/H+6xe8AKpsx5cujL5kU27XrdYm40Rf/rspW83j8gLPPGNZrMNKxQi8UUEOUrUVpiLSkTCJK336pA9Vcs/5zYKh3mRa8qaDIOda7fncLgdLDn37ICOjIrI0oGjk0LNvL1aQSXood/nDFnmtZ76zaVWcv7ewsyJBcXa7q14otMB8NyOgAeXjnq49UqgCu6X3U6s6bavj3NMYl55eR+t9MUEZf5ndjLhf9TCD0PQTf2OZRM=
  secret_access_key:
    secure: t9ZEAkyhcUAsWStIzRiQ8FYmIxGsY5vM9PvGbNKxn4s7G9a3P1Q0ezcQ8lSf3bdBFYe/5F3sM3lRfBc0wrUb3eW/erqoAIbJtY7fR1ASgptvjE35EzWGhanaFnpFyH1anr/hMhlNaZN+w8Csjf+ylI6UUrBOWiGNzCfcfG+7naRIS3wPoIwMvCJYKjV9X5+2XD95xAAqArGwKD7YvUkleFtD+GkSMtogzx5ZC0os89ST46g6sfmkLsxiibVJoCMGNv7AcOp/X8GroZFqVLMMXWa1h0M01QT5J9RvIYiPQISGfKnr2iLeR/6F7/JSqb5HtNQKAQOy6U89Nn4NXBbvxPb6jtxzBjyIEeVrrbMNRk3+ixYNPxRmIumHG5owpNmlDILb7AqvUlVYQep3C9YnGYyEZef5I5EiUq8uQaJW6xCnADZ4eecI5zJVPm4a7RT4rVhQpmZQxiW0Ut6HsuYc6KPX9KSURJ4+gUHcFC4MYKQ4kTmkgGiU5zL9Z57O6w9NL49ARDrxgLXZK+PN5PWVwSZKfyaxqxLVBE1qMFOqGH0rkRDXs0keMYuIOyNFm51eZTCTnmoU22ZlPIRjq1KC93v63N81bL8ivO6H4ZzTVQ2pu7266N5YtScVcadFRqMZce1G+b+a+3O84VACDUN0M7nmT4BVJIOzSBy/eD0d8ys=
  on:
    branch: master
notifications:
  slack:
    secure: AptXFEUQSTTPD5F/E82hMJslA9nk1cOUQOutic2xGDHy9UgTvfilPRuaRU8ERSOSQMdmIi38LXBK9dMOtkIx+pUaR2hKkejWi98pmVAjCujw4MHVfouOklGrqb+6vNETh/ZmD9QB/J8XM77f4O4pkISE4cg0GWf1ngK4L8Uwrgti/6ty5FdDoj15OvzoHHvQFLukXEEIUFKVoOzn3jUespiapGDOzBWCJIRIWjo59NLK+7YvAgsxTcfNTvdAWxIL0IIe1kXhHHQGHLA75SR3wvxY/+ffu6vcUlHIiQDmhDwE+kY8q9Yo3nE3wUpKJPzAv1jE5JhUCwLALuad04ghYtGbsge2NSZTKSDzVH1ecyCR1fUAbvbyq+KDrm3AlfGBeI1Jme5+xNKNVS6FvybxBMqHHSFHSl62G9v2xKoZZMR/MAO6Nz0RrOseq68Yz/PeT+O3jUPz3dmLjrr8ZVv4Mu0seSbVFhiN27Wr5qoObwHwdWRDPWoiKzORxiKY9sC4JkZoMcVV974I7p6rM9fQJCDFl5v9XUT7knY3QB5OACzsmh6nXOAVsR/CIPNEXrauWIkeRj2vEJKsvN+0MVzHvaaFBH0VDQfvL5jpWxWR0eNvEI/5jSA+i0h+EU9nstnFHEAz6ChRrmunojIW5g8gEilfXq4g60VdMzzbxHgZpu4=
